### ISSUE TITLE
Installing this package?

### ISSUE THREAD

**Issue by imkonsowa** [rsocket/rsocket-php#1]
How could I install this package as a composer dependency? I've looked around but couldn't find any commands for that

**Comment by imkonsowa** [comment]
Also tried to execute ```composer require rsocket/rsocket-php``` but it seems this package hasn't published yet.

**Comment by linux-china** [comment]
I'm working on RSocket with PHP 8, and sorry for delay.    https://packagist.org/packages/rsocket/rsocket-php
